services:
    web:
        environment:
            NEAR_SIGNED_AUTH: ${NEAR_SIGNED_AUTH}
            BASE_API_KEY: ${BASE_API_KEY}
            TWITTER_API_KEY: ${TWITTER_API_KEY}
            TWITTER_API_SECRET: ${TWITTER_API_SECRET}
            TWITTER_CLIENT_KEY: ${TWITTER_CLIENT_KEY}
            TWITTER_CLIENT_SECRET: ${TWITTER_CLIENT_SECRET}
            TWITTER_LAST_TIMESTAMP: ${TWITTER_LAST_TIMESTAMP}
            NEXT_PUBLIC_contractId: ${NEXT_PUBLIC_contractId}
            MPC_PUBLIC_KEY_TESTNET: ${MPC_PUBLIC_KEY_TESTNET}
            MPC_PUBLIC_KEY_MAINNET: ${MPC_PUBLIC_KEY_MAINNET}
            CROSSPOST_KEYPAIR : ${CROSSPOST_KEYPAIR}
            CROSSPOST_SIGNER_ID: ${CROSSPOST_SIGNER_ID}
            MASA_API_KEY: ${MASA_API_KEY}
            RESTART_PASS: ${RESTART_PASS}
        platform: linux/amd64 # Explicitly set for TDX
        image: prakharojha/escrow-agent:latest@sha256:0cecbd3135be0ae01142fefe16f2176c8c54ba29440fa9dfe69ff6bcb8777592
        container_name: web
        ports:
            - '3000:3000'
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
        restart: always
