services:
    web:
        environment:
            NEAR_SIGNED_AUTH: ${NEAR_SIGNED_AUTH}
            BASE_API_KEY: ${BASE_API_KEY}
            TWITTER_API_KEY: ${TWITTER_API_KEY}
            TWITTER_API_SECRET: ${TWITTER_API_SECRET}
            TWITTER_CLIENT_KEY: ${TWITTER_CLIENT_KEY}
            TWITTER_CLIENT_SECRET: ${TWITTER_CLIENT_SECRET}
            TWITTER_ACCESS_TOKEN: ${TWITTER_ACCESS_TOKEN}
            TWITTER_REFRESH_TOKEN: ${TWITTER_REFRESH_TOKEN}
            TWITTER_LAST_TIMESTAMP: ${TWITTER_LAST_TIMESTAMP}
            NEXT_PUBLIC_contractId: ${NEXT_PUBLIC_contractId}
            MPC_PUBLIC_KEY_TESTNET: ${MPC_PUBLIC_KEY_TESTNET}
            MPC_PUBLIC_KEY_MAINNET: ${MPC_PUBLIC_KEY_MAINNET}
            RESTART_PASS: ${RESTART_PASS}
        platform: linux/amd64 # Explicitly set for TDX
        image: prakharojha/escrow-agent:latest@sha256:186ce93a221ae77cd9ef294eb0eeed54ef248ae7e35da67536a91f91ff21807f
        container_name: web
        ports:
            - '3000:3000'
        volumes:
            - /var/run/tappd.sock:/var/run/tappd.sock
        restart: always
